import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the dataset
data = pd.read_csv('sensor_data.csv')

# Handle missing values
data.fillna(method='ffill', inplace=True)

# Feature engineering
data['temperature_diff'] = data['temperature'].diff()
data['vibration_diff'] = data['vibration'].diff()
data['pressure_diff'] = data['pressure'].diff()

# Drop rows with NaN values generated by diff()
data.dropna(inplace=True)

# Define features and target
features = data[['temperature', 'vibration', 'pressure', 'temperature_diff', 'vibration_diff', 'pressure_diff']]
target = data['failure']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
